import type { Metadata } from "next"
import { cookies } from "next/headers"
import { Geist, Geist_Mono, Poppins } from "next/font/google"
import "./globals.css"
import { Sidebar, SidebarProvider } from "@/components/ui/sidebar"
import PlaygroundSidebar from "@/components/sideBar"
import Navbar from "@/components/navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})
export const metadata: Metadata = {
  title: "CCHO Testing Playground",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <SidebarProvider defaultOpen={defaultOpen}>
          <div className="flex h-screen w-screen">
            <PlaygroundSidebar />
            <div className="flex flex-col flex-grow">
              <Navbar />
              <div className="flex-grow h-0 overflow-auto flex flex-col">
                <div className="flex-grow flex flex-col h-0">
                  {children}

                  {/* <footer className="text-center text-sm text-neutral-500 p-4">
                  <p>CCHO Playground Testing</p>
                </footer> */}
                </div>
              </div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
